source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0'

project 'CopyDemo.xcodeproj' 

target 'CopyDemo' do
    pod 'Mantle', '~> 2.0' 
    pod 'Masonry'
    pod 'SDWebImage', :path => '/Users/huage/Documents/iOS/Learning/OCLearning/SDWebImage'
end
