platform :ios, '9.0'
inhibit_all_warnings!
 
source 'https://github.com/CocoaPods/Specs.git'

target 'LTReuseableView' do
  
  pod 'SDWebImage'
  pod 'Masonry'
  pod 'LookinServer', :configurations => ['Debug']
  
end
