# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Quartz_2D' do

    pod 'Masonry'

end

target 'Quartz_2DTests' do

end

target 'Quartz_2DUITests' do

end

